server:
  port: 8181
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
spring:
  application:
    name: book-service

http:
  timer:
    enabled: true
    log-level: info
    time-counting: seconds
